# Generated by Django 5.1.5 on 2025-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('emoticon_weather', models.CharField(max_length=10)),
                ('emoticon_emotion', models.CharField(max_length=10)),
                ('emoticon_activity', models.CharField(max_length=10)),
                ('emoticon_daily', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
